name: Create Release
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.1
      - name: Check plugin version
        id: version-check
        run: |
          version=$(sed -n "s/^pluginVersion=\(.*\)$/\1/p" gradle.properties)
          if [ "$version" != "$commit_version" ]; then
            echo "Plugin version does not match commit message"
            exit 0
          fi
      - name: Create Release
        if: needs.build.result == 'success' && steps.check-tag.outputs.tag_exists != '200'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: ${{ env.version }}
          body: ${{ github.event.head_commit.message }}
